modLoader="javafml" 
loaderVersion="[45,)" 
license="MIT"


[[mods]] 
modId="workshop_for_handsome_adventurer_addon_byg" 
version="${file.jarVersion}"  
displayName="Workshop for handsome adventurer - BYG addon" 
authors="MoonFather" 
description='''
Adds racks and 
'''

[[dependencies.workshop_for_handsome_adventurer_addon_byg]]     
    modId="forge"     
    mandatory=true     
    versionRange="[45,)"     
    ordering="NONE"    
    side="BOTH"

[[dependencies.workshop_for_handsome_adventurer_addon_byg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.workshop_for_handsome_adventurer_addon_byg]]
    modId="workshop_for_handsome_adventurer"
    mandatory=true
    versionRange="[1.01,)"
    ordering="AFTER"
    side="BOTH"

#[[dependencies.workshop_for_handsome_adventurer_addon_byg]]
#    modId="byg"
#    mandatory=true
#    versionRange="[4,)"
#    ordering="AFTER"
#    side="BOTH"
